### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by riodda** [ecoppen/futuresboard#40]
Would be nice to have on the the position table also the position size in quote currency.
Currenly is volume and price (need to make the calculation by hand).

**Comment by ecoppen** [comment]
Sure! I assume you mean `position size * position value`. I also want to add % away from next buy/sell so I can do them together.

**Comment by riodda** [comment]
Thanks would be quite cool, don't know if there is a way to fetch current levererage from bybit and show it on the dashboard

**Comment by riodda** [comment]
I've seen you pushed the updates, great job, what is the best way to update ?

**Comment by ecoppen** [comment]
if you go to the `/passivbot` folder and type `git pull` then it'll get the latest changes. From there you can `python -m pip install .` or `python3 -m pip install .` depending on the version of python you're using. Then just restart the board with `futuresboard`

**Comment by riodda** [comment]
Was easy to guess ! :D Thanks !
