### ISSUE TITLE
Publishing in Docker Hub

### ISSUE THREAD

**Issue by donmega** [ecoppen/futuresboard#53]
Hi!

This is a great tool, i am loving it! Would it be possible to for someone to put this on docker hub?

**Comment by rluisr** [comment]
I'm working on PR #69

**Comment by jdmhickey** [comment]
does this work now?

**Comment by jdmhickey** [comment]
i want to be able to run this on a raspberry pi and access it wherever or even host on heroku

**Comment by ecoppen** [comment]
@rluisr did post this to [dockerhub](https://hub.docker.com/r/rluisr/futuresboard) in the past. I've setup an account and will look to automate this in future versions
