### ISSUE TITLE
Support with both short and long

### ISSUE THREAD

**Issue by aumanusorn** [ecoppen/futuresboard#55]
Would it be possible to for someone to add feature support with both short and long.

**Comment by aumanusorn** [comment]
@ecoppen In position short, 
- not display in active section
- not display in all position table

**Comment by aumanusorn** [comment]
@ecoppen I just submitted pull request. Please verify it.

**Comment by aumanusorn** [comment]
after edit as I pull request, I found many things have to edit:

- seperate pbr_short & pbr_long
- seperate buy and sell for short & long position
- position display both short & long position in same time

etc.
@ecoppen

**Comment by ecoppen** [comment]
Makes sense - did you have that already organised for a PR? If not I'll look into it

**Comment by aumanusorn** [comment]
right now, I didn't.

**Comment by aumanusorn** [comment]
> 

I just sent PR, please verify and edit for some my mistake.
