### ISSUE TITLE
IDEA: will kucoin gain support

### ISSUE THREAD

**Issue by jdmhickey** [ecoppen/futuresboard#63]
will kucoin be able to be supported?

**Comment by ecoppen** [comment]
Any API can be integrated into `scraper.py`, so it's just a matter of time. Currently there's a PR for shorts that's being tested but after that there's scope for new exchanges. It looks like passivbot is going to be going for OKX next so there's that also.

[Kucoin API](https://docs.kucoin.com/#general)

**Comment by ecoppen** [comment]
Will not be adding to v1, but will look to make adding new exchanges simpler in v2
