### ISSUE TITLE
/positions URL includes SHORTs where only LONGs are active ( Binance only )

### ISSUE THREAD

**Issue by kkoouu** [ecoppen/futuresboard#66]
For SYMBOLS, where LONG positions are active, /positions URL also displays SHORT row with 0 volume ( probably as well the other way around )

Changing 49th line in positions.html as below does help, however it might be better not to populate positions array with zero valued positions, probably somewhere in blueprint.py ( I'm not that familiar with python syntax )
```

49c49
<                     {% if positions[coin][0]|length > 1 %}
---
>                     {% if positions[coin][0]|length > 1 and positions[coin][0][1][6] != 0 %}


```

**Comment by ecoppen** [comment]
This is sensible, will take a look at some options

**Comment by ecoppen** [comment]
Not addressing in v1 but will look to solve in v2
