### ISSUE TITLE
Some route error with Nginx

### ISSUE THREAD

**Issue by hungud** [ecoppen/futuresboard#7]
Dear Pro,

Thank you for your dashboard. All things are nice

I'm testing some routes not working

/history/
0|futuresb |     return self._get_source_fast(environment, template)
0|futuresb |   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 95, in _get_source_fast
0|futuresb |     raise TemplateNotFound(template)
0|futuresb | jinja2.exceptions.TemplateNotFound: history.html
0|futuresb | 127.0.0.1 - - [18/Nov/2021 00:12:37] "GET /history/ HTTP/1.1" 500 -

and others not important: 
- /coins/active
- /coins/inactive
- /coins/totals

**Comment by ecoppen** [comment]
/coins/active
/coins/inactive
/coins/totals

Are a result of changing the way that the 'active coins' are discovered, so these are indeed deprecated - I will remove.

/history/ was a work in progress now forgotten - I will remove and then rework later

**Comment by hungud** [comment]
Okay, 

Thank you for your information. I have understood. All things are nice 🍡
