### ISSUE TITLE
site https://www.futuresboard.xyz/ 

### ISSUE THREAD

**Issue by ka1myk** [ecoppen/futuresboard#75]
Hello! https://www.futuresboard.xyz/ is not available

**Comment by ecoppen** [comment]
hmm [http://www.futuresboard.xyz/](http://www.futuresboard.xyz/) still works, I'll look into it!

**Comment by ka1myk** [comment]
Maybe http://www.futuresboard.xyz/ is closed from RU? IP 188.255.34.222

**Comment by ecoppen** [comment]
Website is offline now, I'll upload a copy of the potential server setup to github pages.
